# forms/utils/us_state_select_field.py
from wtforms import SelectField
from wtforms.validators import DataRequired


def ny_county_select_field():
    return SelectField(
        "Commissioned County",
        choices=[
            ("Albany", "Albany County"),
            ("Allegany", "Allegany County"),
            ("Bronx", "Bronx County"),
            ("Broome", "Broome County"),
            ("Cattaraugus", "Cattaraugus County"),
            ("Cayuga", "Cayuga County"),
            ("Chautauqua", "Chautauqua County"),
            ("Chemung", "Chemung County"),
            ("Chenango", "Chenango County"),
            ("Clinton", "Clinton County"),
            ("Columbia", "Columbia County"),
            ("Cortland", "Cortland County"),
            ("Delaware", "Delaware County"),
            ("Dutchess", "Dutchess County"),
            ("Erie", "Erie County"),
            ("Essex", "Essex County"),
            ("Franklin", "Franklin County"),
            ("Fulton", "Fulton County"),
            ("Genesee", "Genesee County"),
            ("Greene", "Greene County"),
            ("Hamilton", "Hamilton County"),
            ("Herkimer", "Herkimer County"),
            ("Jefferson", "Jefferson County"),
            ("Kings", "Kings County (Brooklyn)"),
            ("Lewis", "Lewis County"),
            ("Livingston", "Livingston County"),
            ("Madison", "Madison County"),
            ("Monroe", "Monroe County"),
            ("Montgomery", "Montgomery County"),
            ("Nassau", "Nassau County"),
            ("New York", "New York County (Manhattan)"),
            ("Niagara", "Niagara County"),
            ("Oneida", "Oneida County"),
            ("Onondaga", "Onondaga County"),
            ("Ontario", "Ontario County"),
            ("Orange", "Orange County"),
            ("Orleans", "Orleans County"),
            ("Oswego", "Oswego County"),
            ("Otsego", "Otsego County"),
            ("Putnam", "Putnam County"),
            ("Queens", "Queens County"),
            ("Rensselaer", "Rensselaer County"),
            ("Richmond", "Richmond County (Staten Island)"),
            ("Rockland", "Rockland County"),
            ("Saint Lawrence", "Saint Lawrence County"),
            ("Saratoga", "Saratoga County"),
            ("Schenectady", "Schenectady County"),
            ("Schoharie", "Schoharie County"),
            ("Schuyler", "Schuyler County"),
            ("Seneca", "Seneca County"),
            ("Steuben", "Steuben County"),
            ("Suffolk", "Suffolk County"),
            ("Sullivan", "Sullivan County"),
            ("Tioga", "Tioga County"),
            ("Tompkins", "Tompkins County"),
            ("Ulster", "Ulster County"),
            ("Warren", "Warren County"),
            ("Washington", "Washington County"),
            ("Wayne", "Wayne County"),
            ("Westchester", "Westchester County"),
            ("Wyoming", "Wyoming County"),
            ("Yates", "Yates County"),
        ],
        validators=[DataRequired()],
    )
