"""empty message

Revision ID: 207efcedc09d
Revises: 7c2b7007144f
Create Date: 2024-05-28 10:15:25.556375

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "207efcedc09d"
down_revision = "7c2b7007144f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_details", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "timezone", sa.String(length=50), nullable=False, server_default="UTC"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_details", schema=None) as batch_op:
        batch_op.drop_column("timezone")

    # ### end Alembic commands ###
