"""Added notary_credentials table

Revision ID: 67a67ef6db29
Revises: 
Create Date: 2024-05-17 14:40:02.471092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a67ef6db29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Notaries')
    op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.create_table('Notaries',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Notaries_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('commission_holder_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('commission_number_uid', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('business_name_if_available', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('business_address_1_if_available', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('business_address_2_if_available', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('business_city_if_available', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('business_state_if_available', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('business_zip_if_available', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('commissioned_county', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('commission_type_traditional_or_electronic', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('term_issue_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('term_expiration_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Notaries_pkey'),
    sa.UniqueConstraint('commission_number_uid', name='Notaries_commission_number_uid_key')
    )
    # ### end Alembic commands ###
