"""Initial migration

Revision ID: 7c2b7007144f
Revises: 
Create Date: 2024-05-26 13:47:54.019724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2b7007144f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notarial_act', schema=None) as batch_op:
        batch_op.add_column(sa.Column('principal_credential_type', sa.String(length=100), nullable=True))
        batch_op.drop_column('credential_type')
        batch_op.drop_column('other_act_type_input')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notarial_act', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_act_type_input', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('credential_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('principal_credential_type')

    # ### end Alembic commands ###
