"""add filepath column

Revision ID: f9d8912d8b47
Revises: 80f210d4c45d
Create Date: 2024-06-07 14:14:37.690969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d8912d8b47'
down_revision = '80f210d4c45d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.String(length=500), nullable=True))
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_column('filepath')

    # ### end Alembic commands ###
